import 'package:commodity/utilitis/colors.dart';
import 'package:flutter/material.dart';
TextStyle T10textStyle = const TextStyle(fontFamily: 'Font2',fontSize: 12,fontStyle: FontStyle.normal,fontWeight: FontWeight.w500,color: AppTheme.lightblack);
TextStyle T1textStyle = const TextStyle(fontSize: 20,fontStyle: FontStyle.normal,fontWeight: FontWeight.w700,fontFamily: 'Font2',color: AppTheme.Primarycolor);
TextStyle T2textStyle = const TextStyle(fontSize: 14,fontStyle: FontStyle.normal,fontWeight: FontWeight.w900,fontFamily: 'Font1',color: AppTheme.black);
TextStyle T3textStyle = const TextStyle(fontSize: 14,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.secondarycolor);
TextStyle T4textStyle = const TextStyle(fontSize: 14,fontStyle: FontStyle.normal,fontWeight: FontWeight.w500,fontFamily: 'Font1',color: AppTheme.rgb);
TextStyle T5textStyle = const TextStyle(fontSize: 15,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.RGB);
TextStyle T6textStyle = const TextStyle(fontSize: 13,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.secondarycolor);
TextStyle T7textStyle = const TextStyle(fontSize: 13,fontStyle: FontStyle.normal,fontWeight: FontWeight.w500,fontFamily: 'Font1',color: AppTheme.Rgb);
TextStyle T8textStyle = const TextStyle(fontSize: 14,fontStyle: FontStyle.normal,fontWeight: FontWeight.w500,fontFamily: 'Font1',color: AppTheme.Primarycolor);
TextStyle T9textStyle = const TextStyle(fontFamily: 'Font1',fontWeight: FontWeight.w600,fontSize: 16,fontStyle: FontStyle.normal,color: AppTheme.white);
TextStyle T11textStyle = const TextStyle(fontSize: 18,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.Primarycolor);
TextStyle T12textStyle = const TextStyle(fontSize: 14,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.black);
TextStyle T13textStyle = const TextStyle(fontSize: 20,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.black);
TextStyle T14textStyle = const TextStyle(fontSize: 24,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.white);
TextStyle T15textStyle = const TextStyle(fontSize: 30,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.white);
TextStyle T16textStyle = const TextStyle(fontSize: 14,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1');
TextStyle T17textStyle = const TextStyle(fontSize: 20,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1');
TextStyle T18textStyle = const TextStyle(fontSize: 18,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1');
TextStyle T19textStyle = const TextStyle(fontSize: 30,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.white);
TextStyle T20textStyle = const TextStyle(fontSize: 14,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.white);
TextStyle T21textStyle = const TextStyle(fontSize: 12,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.OffWhite);
TextStyle T22textStyle = const TextStyle(fontSize: 20,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.white);
TextStyle T23textStyle = const TextStyle(fontSize: 14,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.red);
TextStyle T24textStyle = const TextStyle(fontSize: 18,fontStyle: FontStyle.normal,fontWeight: FontWeight.w500,fontFamily: 'Font1',color: AppTheme.lightblack);
TextStyle T25textStyle = const TextStyle(fontSize: 12,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.lightblack);
TextStyle T26textStyle = const TextStyle(fontSize: 15,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.lightblack);
TextStyle T27textStyle = const TextStyle(fontSize: 16,fontStyle: FontStyle.normal,fontWeight: FontWeight.w500,fontFamily: 'Font1');
TextStyle T28textStyle = const TextStyle(fontSize: 16,fontStyle: FontStyle.normal,fontWeight: FontWeight.w700,fontFamily: 'Font1',color: AppTheme.black);
TextStyle T29textStyle = const TextStyle(fontSize: 13,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.Fontcolor);
TextStyle T30textStyle = const TextStyle(fontSize: 12,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.green);
TextStyle T31textStyle = const TextStyle(fontSize: 9,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.RGB);
TextStyle T32textStyle = const TextStyle(fontSize: 12,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.lightblack);
TextStyle T33textStyle = const TextStyle(fontSize: 20,fontStyle: FontStyle.normal,fontWeight: FontWeight.w500,fontFamily: 'Font2');
TextStyle T34textStyle = const TextStyle(fontSize: 15,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.rgb);
TextStyle T35textStyle = const TextStyle(fontSize: 30,fontStyle: FontStyle.normal,fontWeight: FontWeight.w600,fontFamily: 'Font1',color: AppTheme.lightblack);
TextStyle T36textStyle = const TextStyle(fontSize: 16,fontStyle: FontStyle.normal,fontWeight: FontWeight.w500,fontFamily: 'Font1',color: AppTheme.green);
//TextStyle T32textStyle = const TextStyle(fontSize: 12,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.lightblack);
//TextStyle T32textStyle = const TextStyle(fontSize: 12,fontStyle: FontStyle.normal,fontWeight: FontWeight.w400,fontFamily: 'Font1',color: AppTheme.lightblack);



