// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLr_YSLPq8-zmt5ilIEF4XlYmJthPtbU',
    appId: '1:480777956615:web:a3c4586320cc7413f569a2',
    messagingSenderId: '480777956615',
    projectId: 'commodity-ec778',
    authDomain: 'commodity-ec778.firebaseapp.com',
    storageBucket: 'commodity-ec778.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIBVQ92RaPokfmtvfGCdaSZbtG3pK_n6k',
    appId: '1:480777956615:android:c3f3561018cb0c80f569a2',
    messagingSenderId: '480777956615',
    projectId: 'commodity-ec778',
    storageBucket: 'commodity-ec778.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF06NXSoteKnjUaDX6DWmxiDTupbnYqMM',
    appId: '1:480777956615:ios:76cf4eb6b3aee39cf569a2',
    messagingSenderId: '480777956615',
    projectId: 'commodity-ec778',
    storageBucket: 'commodity-ec778.appspot.com',
    iosBundleId: 'com.example.commodity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF06NXSoteKnjUaDX6DWmxiDTupbnYqMM',
    appId: '1:480777956615:ios:b835c48fc28ff8b5f569a2',
    messagingSenderId: '480777956615',
    projectId: 'commodity-ec778',
    storageBucket: 'commodity-ec778.appspot.com',
    iosBundleId: 'com.example.commodity.RunnerTests',
  );
}
